### ISSUE TITLE
DTC messages should not be dependent of C structure packing.

### ISSUE THREAD

**Issue by vbmithr** [DTC-protocol/DTC#11]
Currently, the DTC messages are defined for the C/C++ language, and the actual messages that Sierra Chart expect is dependent on the C compiler used.

Using OCaml, I need to guess how the compiler SC uses will pack those data structures.
I'm interested to know how SC deserialize those structures: just take the memory and cast that into a structure (I guess it is how it is done).

So basically, instead of relying on the compiler, I would prefer having a clear definition of the size of all messages and the position of those messages in memory (don't want to guess padding).

**Comment by SierraChart** [comment]
These are the relevant references:
https://en.wikipedia.org/wiki/Data_structure_alignment
https://msdn.microsoft.com/en-us/library/xh3e3fd0.aspx

The header file specifies #pragma pack(8)

"just take the memory and cast that into a structure".

Yes this is correct.

**Comment by vbmithr** [comment]
Ok, fair enough.
